; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = teensy41

[common]
build_flags =
    -D USB_MTPDISK_SERIAL

[env:teensy41]
platform = teensy@5.0.0
board = teensy41
framework = arduino
build_flags =
    ${common.build_flags}
    -D ENABLE_TELEMETRY=0
lib_ldf_mode = deep
lib_deps =
    https://github.com/KurtE/MTP_Teensy.git#13ae26f39f6d9f3b690950dfb96ed0f79ee436d1
    latimes2/InternalTemperature@^2.1.1-a
    https://github.com/blongworth/flasher-library.git#ae81a3d3880709a8b8b2c5bb14775a81fabfd17e
    adafruit/Adafruit INA260 Library@^1.5.3
    ssilverman/QNEthernet@0.37.0

[env:teensy41_telemetry]
extends = env:teensy41
build_flags =
    ${common.build_flags}
    -D ENABLE_TELEMETRY=1
